apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: grapi.grsf.grpl.io
  labels:
    crossplane.io/xrd: compositegrappleapis.grsf.grpl.io
    provider: grapi
spec:
  # writeConnectionSecretsToNamespace: grpl-system
  compositeTypeRef:
    apiVersion: grsf.grpl.io/v1alpha1
    kind: CompositeGrappleApi
  resources:
    # - base:
    #     apiVersion: kubernetes.crossplane.io/v1alpha1
    #     kind: Object
    #     spec:
    #       forProvider:
    #         manifest:
    #           apiVersion: v1
    #           kind: Pod
    #           metadata:
    #             name: mypod
    #             namespace: grpl-test
    #           spec:
    #             containers:
    #             - image: nginx:latest
    #               name: mypod
    #       writeConnectionSecretsToRef: 
    #         namespace: grpl-test
    #         name: mypod-secret
    #       providerConfigRef: 
    #         # name: providerconfigs.kubernetes.crossplane.io/kubernetes-provider
    #         name: kubernetes-provider
    #   patches:
    #     - fromFieldPath: metadata.namespace
    #       toFieldPath: metadata.namespace
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations: 
            crossplane.io/external-name: # patched
        spec:
          forProvider:
            chart:
              name: grapi
              repository: oci://public.ecr.aws/p7h7z5g3
              version: 0.1.3
            namespace: # patched
            values:
              name: # patched
              asname: ""
              grapiversion: "0.0.1"
              clusterdomain: ""
              ingress: false
              ssl: false
              sslissuer: letsencrypt-prod-cloud20x
              disableexplorer: false
              buildimages: false
              buildimagecache: true
              runimages: true
              deployimages: false
              imagetag: ""
              # beimage: patrickriegler/loopback
              # beimagetag: v0.97
              rediscache: false
              translations: false
              apiregistry: false
              graphql: false
              monitoring: false
              discoveredrepos: true
              externalsecrets: []
              datasources: []
              discoveries: []
              models: []
              relations: []
              serviceproviders: []
              openapis: []
              restcruds: []
              repositories: []
              controllers: []
              prepatches: []
              prediscoverypatches: []
              prerelationpatches: []
              postpatches: []
            set: 
              - name: grapiversion
                valueFrom:
                  secretKeyRef: 
                    name: grsf-config
                    namespace: grpl-system
                    key: grapiversion
              - name: clusterdomain
                valueFrom:
                  secretKeyRef: 
                    name: grsf-config
                    namespace: grpl-system
                    key: clusterdomain
              - name: sslissuer
                valueFrom:
                  secretKeyRef: 
                    name: grsf-config
                    namespace: grpl-system
                    key: sslissuer
              - name: beimage_config
                valueFrom:
                  secretKeyRef: 
                    name: grsf-config
                    namespace: grpl-system
                    key: beimage
              - name: beimagetag_config
                valueFrom:
                  secretKeyRef: 
                    name: grsf-config
                    namespace: grpl-system
                    key: beimagetag
            # set: 
            #   - name: externalDatabase.host
            #     valueFrom: 
            #       secretKeyRef: 
            #         name: 
            #         namespace: grpl-system
            #         key: endpoint
            #   - name: externalDatabase.user
            #     valueFrom: 
            #       secretKeyRef: 
            #         name: 
            #         namespace: grpl-system
            #         key: username
            #   - name: externalDatabase.password
            #     valueFrom: 
            #       secretKeyRef: 
            #         name: 
            #         namespace: grpl-system
            #         key: password
          writeConnectionSecretsToRef: 
            namespace: grpl-test
            name: myrelease-secret
          providerConfigRef: 
            # name: providerconfigs.helm.crossplane.io/helm-provider-config
            name: helm-provider-config
      patches:
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.namespace
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.claimRef.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          policy:
            fromFieldPath: Required
          transforms:
            - type: string
              string:
                fmt: "%s-grapi"
        - fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.values.name
          policy:
            fromFieldPath: Required
          transforms:
            - type: string
              string:
                fmt: "%s-grapi"
        - fromFieldPath: spec.asname
          toFieldPath: spec.forProvider.values.asname
        - fromFieldPath: spec.grapiversion
          toFieldPath: spec.forProvider.values.grapiversion
        - fromFieldPath: spec.clusterdomain
          toFieldPath: spec.forProvider.values.clusterdomain
        - fromFieldPath: spec.ingress
          toFieldPath: spec.forProvider.values.ingress
        - fromFieldPath: spec.ssl
          toFieldPath: spec.forProvider.values.ssl
        - fromFieldPath: spec.sslissuer
          toFieldPath: spec.forProvider.values.sslissuer
        - fromFieldPath: spec.sslissuer
          toFieldPath: spec.forProvider.values.sslissuer
        - fromFieldPath: spec.disableexplorer
          toFieldPath: spec.forProvider.values.disableexplorer
        - fromFieldPath: spec.buildimages
          toFieldPath: spec.forProvider.values.buildimages
        - fromFieldPath: spec.buildimagecache
          toFieldPath: spec.forProvider.values.buildimagecache
        - fromFieldPath: spec.runimages
          toFieldPath: spec.forProvider.values.runimages
        - fromFieldPath: spec.deployimages
          toFieldPath: spec.forProvider.values.deployimages
        - fromFieldPath: spec.imagetag
          toFieldPath: spec.forProvider.values.imagetag
        - fromFieldPath: spec.beimage
          toFieldPath: spec.forProvider.values.beimage
        - fromFieldPath: spec.beimagetag
          toFieldPath: spec.forProvider.values.beimagetag
        - fromFieldPath: spec.rediscache
          toFieldPath: spec.forProvider.values.rediscache
        - fromFieldPath: spec.translations
          toFieldPath: spec.forProvider.values.translations
        - fromFieldPath: spec.apiregistry
          toFieldPath: spec.forProvider.values.apiregistry
        - fromFieldPath: spec.graphql
          toFieldPath: spec.forProvider.values.graphql
        - fromFieldPath: spec.monitoring
          toFieldPath: spec.forProvider.values.monitoring
        - fromFieldPath: spec.discoveredrepos
          toFieldPath: spec.forProvider.values.discoveredrepos
        - fromFieldPath: spec.externalsecrets
          toFieldPath: spec.forProvider.values.externalsecrets

        - fromFieldPath: spec.datasources
          toFieldPath: spec.forProvider.values.datasources
        - fromFieldPath: spec.discoveries
          toFieldPath: spec.forProvider.values.discoveries
        - fromFieldPath: spec.models
          toFieldPath: spec.forProvider.values.models
        - fromFieldPath: spec.relations
          toFieldPath: spec.forProvider.values.relations
        - fromFieldPath: spec.serviceproviders
          toFieldPath: spec.forProvider.values.serviceproviders
        - fromFieldPath: spec.openapis
          toFieldPath: spec.forProvider.values.openapis
        - fromFieldPath: spec.restcruds
          toFieldPath: spec.forProvider.values.restcruds
        - fromFieldPath: spec.repositories
          toFieldPath: spec.forProvider.values.repositories
        - fromFieldPath: spec.controllers
          toFieldPath: spec.forProvider.values.controllers
        - fromFieldPath: spec.prepatches
          toFieldPath: spec.forProvider.values.prepatches
        - fromFieldPath: spec.prediscoverypatches
          toFieldPath: spec.forProvider.values.prediscoverypatches
        - fromFieldPath: spec.prerelationpatches
          toFieldPath: spec.forProvider.values.prerelationpatches
        - fromFieldPath: spec.postpatches
          toFieldPath: spec.forProvider.values.postpatches
