apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: grapi.gsf.grpl.io
  labels:
    crossplane.io/xrd: compositegrappleapis.gsf.grpl.io
    provider: grapi
spec:
  # writeConnectionSecretsToNamespace: grpl-system
  compositeTypeRef:
    apiVersion: gsf.grpl.io/v1alpha1
    kind: CompositeGrappleApi
  resources:
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Pod
              metadata:
                name: mypod
                namespace: grpl-test
              spec:
                containers:
                - image: nginx:latest
                  name: mypod
          providerConfigRef: 
            name: kubernetes-provider
      # patches:
      #   - fromFieldPath: spec.id
      #     toFieldPath: metadata.labels[networks.multik8s.platformref.crossplane.io/network-id]
