apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gr.grsf.grpl.io
  labels:
    crossplane.io/xrd: compositegrappleresources.grsf.grpl.io
    provider: gr
spec:
  compositeTypeRef:
    apiVersion: grsf.grpl.io/v1alpha1
    kind: CompositeGrappleResource
  mode: Pipeline
  pipeline:
  - step: check-function-resource-readiness
    functionRef:
      name: crossplane-contrib-function-auto-ready
  # - step: run-the-dummy-function
  #   functionRef:
  #     name: crossplane-contrib-function-dummy
  #   # input:
  #   #   apiVersion: dummy.fn.crossplane.io/v1beta1
  #   #   kind: Response
  #   #   response:
  #   #     value: true
  - step: run-the-template
    functionRef:
      name: grpl-grsf-lic
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Input
      email: "zahid.iqbal.marth.1998@gmail.com"
    # readinessChecks:
    #   - type: None
