apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositegrappleresource.grsf.grpl.io
spec:
  claimNames:
    kind: GrappleResource
    plural: grappleresources
    shortNames:
    - gr
    - gresoure
  group: grsf.grpl.io
  names:
    kind: CompositeGrappleResource
    plural: compositegrappleresources
    shortNames:
    - xgr
    - xgresoure
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: |
                  Specification of the desired behavior of the grapple resource (gr). 
              properties:
                namespace:
                  description: |
                    Define the namespace of the grapple resource
                  type: string
                type:
                  description: | 
                    Type of the grapple resource
                    (Default: "gras")
                  type: string
                name:
                  description: | 
                    Name of the grapple resource
                    (Default: "")
                  type: string
