apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: grsf.grsf.grpl.io
  labels:
    crossplane.io/xrd: compositegrapplesolutionframeworks.grsf.grpl.io
    provider: grsf
spec:
  # writeConnectionSecretsToNamespace: grpl-system
  compositeTypeRef:
    apiVersion: grsf.grpl.io/v1alpha1
    kind: GrappleSolutionFramework
  resources:
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations: 
            crossplane.io/external-name: # patched
        spec:
          forProvider:
            chart:
              name: grsf
              repository: oci://public.ecr.aws/p7h7z5g3
              version: 0.1.0
            namespace: # patched
            values:
              clusterdomain: ""
              external-secrets: ""
          writeConnectionSecretsToRef: 
            namespace: grpl-system
            name: grsf-secret
          providerConfigRef: 
            # name: providerconfigs.helm.crossplane.io/helm-provider-config
            name: helm-provider-config
      patches:
        - fromFieldPath: spec.claimRef.namespace
          toFieldPath: spec.forProvider.namespace
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.claimRef.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.values.name
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.external-secrets
          toFieldPath: spec.forProvider.values.external-secrets
