apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: crossplane
  namespace: grpl-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-provider-helm-clusterrolebinding
subjects:
- kind: Group
  name: system:serviceaccounts:grpl-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
